name: Auto-Archive
on:
  schedule:
    - cron: '0 0 * * 0'  # Sundays at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Archive old files
      - name: Move outdated content
        run: |
          mkdir -p docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))
          find docs/news/current/ -name "*.html" ! -name "index.html" -mtime +180 \
            -exec mv {} docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))/ \;

      # 2. Update indexes
      - name: Regenerate indexes
        run: |
          # Current index
          echo '<ul>' > docs/news/current/index.html
          find docs/news/current/ -maxdepth 1 -name "*.html" ! -name "index.html" | while read file; do
            echo "<li><a href='$(basename "$file")'>$(basename "$file" .html)</a></li>" >> docs/news/current/index.html
          done

          # Archive index
          echo '<ul>' > docs/news/archived/index.html
          find docs/news/archived/ -name "*.html" ! -path "*/index.html" | while read file; do
            rel_path=${file#docs/news/archived/}
            echo "<li><a href='$rel_path'>$rel_path</a></li>" >> docs/news/archived/index.html
          done

      # 3. Push changes
      - name: Commit updates
        run: |
          git config --global user.name "Auto-Archiver"
          git add .
          git commit -m "🔧 Auto-archive $(date +%F)"
          git push