- name: Generate Indexes
  run: |
    # Generate CURRENT index
    echo '<!DOCTYPE html><html><head><title>Current ROMs</title></head><body><ul>' > docs/news/current/index.html
    find docs/news/current/ -maxdepth 1 -name '*.html' ! -name 'index.html' | while read file; do
      title=$(basename "$file" .html | sed 's/-/ /g')
      echo "<li><a href='$(basename "$file")'>$title</a></li>" >> docs/news/current/index.html
    done
    echo '</ul></body></html>' >> docs/news/current/index.html

    # Generate ARCHIVED index
    echo '<!DOCTYPE html><html><head><title>Archived ROMs</title></head><body><ul>' > docs/news/archived/index.html
    find docs/news/archived/ -type f -name '*.html' ! -name 'index.html' | while read file; do
      rel_path=${file#docs/news/archived/}
      title=$(basename "$file" .html | sed 's/-/ /g')
      echo "<li><a href='$rel_path'>$title</a></li>" >> docs/news/archived/index.html
    done
    echo '</ul></body></html>' >> docs/news/archived/index.html