name: Backup System
on:
  schedule:
    - cron: '0 0 * * 0'  # Sundays midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # Grants GITHUB_TOKEN write access

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout with persistent credentials
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # Essential for push access
          fetch-depth: 0            # Get full history for proper dating

      # 2. Archive old posts (>180 days)
      - name: Archive outdated content
        run: |
          # Create quarterly archive folder (e.g., 2024/Q3)
          mkdir -p docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))
          
          # Move old files (safe for spaces in filenames)
          find docs/news/current/ -name "*.html" ! -name "index.html" -mtime +180 -print0 | \
            xargs -0 -I {} mv {} docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))/

      # 3. Rebuild indexes
      - name: Update indexes
        run: |
          # Current News Index
          echo '<!DOCTYPE html><html><head><title>Current ROMs</title></head><body><ul>' > docs/news/current/index.html
          find docs/news/current/ -maxdepth 1 -name "*.html" ! -name "index.html" | sort | while read file; do
            clean_name=$(basename "$file" .html | sed 's/-/ /g')
            echo "<li><a href='$(basename "$file")'>$clean_name</a></li>" >> docs/news/current/index.html
          done
          echo '</ul></body></html>' >> docs/news/current/index.html

          # Archived News Index
          echo '<!DOCTYPE html><html><head><title>Archived ROMs</title></head><body><ul>' > docs/news/archived/index.html
          find docs/news/archived/ -name "*.html" ! -name "index.html" | sort -r | while read file; do
            rel_path=${file#docs/news/archived/}
            clean_name=$(basename "$file" .html | sed 's/-/ /g')
            year=$(echo "$rel_path" | cut -d'/' -f1)
            echo "<li><a href='$rel_path'>$clean_name</a> <small>($year)</small></li>" >> docs/news/archived/index.html
          done
          echo '</ul></body></html>' >> docs/news/archived/index.html

      # 4. Commit and push changes
      - name: Push updates
        run: |
          git config --global user.name "Backup Bot"
          git config --global user.email "backup@exynos-news"
          git add .
          git commit -m "🤖 Auto-backup $(date +'%Y-%m-%d %H:%M')"
          git push
