name: Backup System
on:
  schedule:
    - cron: '0 0 * * 0'  # Sundays midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Archive old posts (single command)
      - name: Archive outdated
        run: |
          mkdir -p docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))
          find docs/news/current/ -name "*.html" ! -name "index.html" -mtime +180 -exec mv -t docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))/ {} +

      # Unified index generation
      - name: Rebuild indexes
        run: |
          # Shared functions
          html_header() {
            echo "<!DOCTYPE html>
            <html>
            <head>
              <title>$1</title>
              <link rel=\"stylesheet\" href=\"../../assets/crt.css\">
            </head>
            <body>
              <div class=\"container\">
                <h1>> $1_</h1>
                <ul>"
          }

          html_footer() {
            echo "    </ul>
                <p>> <a href=\"../\">Back to home</a>_</p>
              </div>
            </body>
            </html>"
          }

          process_files() {
            find "$1" -name "*.html" ! -name "index.html" -printf "%T@\t%p\n" |
            sort -nr |
            cut -f2- |
            while IFS= read -r file; do
              title=$(basename "${file%.html}" | tr '-' ' ')
              date=$(date -r "$file" +"%Y-%m-%d")
              if [ "$1" = "docs/news/current" ]; then
                echo "      <li><a href=\"$(basename "$file")\">$title</a> <small>| $date</small></li>"
              else
                echo "      <li><a href=\"${file#docs/news/archived/}\">$title</a> <small>| $date</small></li>"
              fi
            done
          }

          # Current index
          html_header "Current Stuff" > docs/news/current/index.html
          process_files "docs/news/current" >> docs/news/current/index.html
          html_footer >> docs/news/current/index.html

          # Archive index
          html_header "Archived Stuff" > docs/news/archived/index.html
          process_files "docs/news/archived" >> docs/news/archived/index.html
          html_footer >> docs/news/archived/index.html

      - name: Commit changes
        run: |
          git config --global user.name "Backup Bot"
          git config --global user.email "backup@exynos-news"
          git add .
          git commit -m "Auto Index $(date +'%Y-%m-%d')"
          git push
