name: Backup System
on:
  schedule:
    - cron: '0 0 * * 0'  # Sundays midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # Archive old posts
      - name: Move outdated content
        run: |
          mkdir -p docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))
          find docs/news/current/ -name "*.html" ! -name "index.html" -mtime +180 -exec mv {} docs/news/archived/$(date +%Y)/Q$(($(date +%m)/3+1))/ \;

      # Update indexes in your preferred format
      - name: Update Current Index
        run: |
          cat > docs/news/current/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Current Stuff</title>
            <link rel="stylesheet" href="../../assets/crt.css">
          </head>
          <body>
            <div class="container">
              <h1>> Current Stuff_</h1>
              <ul>
          EOF

          # Add current posts to index
          find docs/news/current/ -maxdepth 1 -name "*.html" ! -name "index.html" | while read file; do
            title=$(basename "$file" .html | sed -E 's/(.*)-([^-]+)$/\1 by \2/' | sed 's/-/ /g')
            echo "        <li><a href=\"$(basename "$file")\">$title</a></li>" >> docs/news/current/index.html
          done

          cat >> docs/news/current/index.html << 'EOF'
              </ul>
              <p>> <a href="../">Back to home</a>_</p>
            </div>
          </body>
          </html>
          EOF

      - name: Update Archive Index
        run: |
          cat > docs/news/archived/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Archived Stuff</title>
            <link rel="stylesheet" href="../../assets/crt.css">
          </head>
          <body>
            <div class="container">
              <h1>> Archived Stuff_</h1>
              <ul>
          EOF

          # Add archived posts to index
          find docs/news/archived/ -name "*.html" ! -name "index.html" | sort -r | while read file; do
            rel_path=${file#docs/news/archived/}
            title=$(basename "$file" .html | sed -E 's/(.*)-([^-]+)$/\1 by \2/' | sed 's/-/ /g')
            year=$(dirname "$rel_path" | cut -d'/' -f1)
            echo "        <li><a href=\"$rel_path\">$title</a> <small>($year)</small></li>" >> docs/news/archived/index.html
          done

          cat >> docs/news/archived/index.html << 'EOF'
              </ul>
              <p>> <a href="../">Back to home</a>_</p>
            </div>
          </body>
          </html>
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "Backup Bot"
          git config --global user.email "backup@exynos-news"
          git add .
          git commit -m "🤖 Auto-backup $(date +'%Y-%m-%d %H:%M')"
          git push
